services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
  ui:
    build:
      context: ui
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui:/app
    ports:
      - 5173:5173
    environment:
      - VITE_ENDPOINT_BASE_URL=/linguflow-api
    links:
      - api:linguflow-api
    depends_on:
      - api
