name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:

        1. Step 1
        2. Step 2
        3. ...
        4. See error
      placeholder: How can we replicate the issue?
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and logs
      description: If applicable, add screenshots and logs to help explain your problem.
      placeholder: Add screenshots here
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      # There is no version information for the project now, but it can be added later
      description: |
        - Operating System: <!-- Specify the OS (e.g., Windows 10, Ubuntu 20.04) -->
        - Browser: <!-- Specify the Browser (e.g. Chrome v121.0) -->
        - Python Version: <!-- Specify the Python version (e.g., 3.8) -->
        - Node Version: <!-- Specify the Node version (e.g., 14.17.0) -->
        - Related Issues: <!-- Link to any related issues here (e.g., #1) -->
        - Any other relevant information.
      placeholder: Any additional details