name: CI UI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "ui"

      - name: Install yarn
        uses: mskelton/setup-yarn@v1

      - name: Set node version to 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - run: yarn

      - name: Run lint
        run: yarn lint
